/*
The query combines data from the "employees," "orders," and "order_details" tables. It calculates the total revenue generated by each employee based on the products they sold. The query groups the results by employee ID, first name, and last name to provide a summary of total revenue for each employee.
*/
SELECT employees.employee_id, employees.first_name, employees.last_name,
SuM(order_details.quantity * order_details.unit_price) AS TotalRevenue
FROM employees
JOIN orders ON employees.employee_id = orders.employee_id
JOIN order_details ON orders.order_id = order_details.order_id
GROUP BY employees.employee_id, employees. first_name, employees.last_name;